### ISSUE TITLE
production config(s)

### ISSUE THREAD

**Issue by argyleink** [argyleink/shortstack#4]
can't decide if this should provide them or not. crunching for prod usually takes a bit of custom work and i'm happy letting me or other folks add that feature when they're ready and meeting the requirements/budgets that they've set at a project level. thoughts!?

**Comment by nucliweb** [comment]
I think that is a good approach, production config(s), to offer an architecture of folder to production.
Now you add the CSS and JS bundles in the same folder that the development files.

You can confuse the newbie folks, and then they upload all files to production.

An option is:
```
/app (or /src because as a standard) To develop files
/dist To production files
```

My approach for the src folder should be:
```
/src/assets/
/src/css/index.css
/src/js/indes.js
/src/index.html
```

I have a similar boilerplate but without JS bundler (by the moment) 👉🏼https://github.com/nucliweb/Komenco
